[project]
name = "emotion-inference"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "torch>=2.0.0",
    "transformers>=4.20.0",
    "pillow",
    "opencv-python",
    "numpy",
]
